apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      automountServiceAccountToken: false
      containers:
      - name: backend-app
        image: sachinthokal/skillpulse-backend:latest
        ports:
        - containerPort: 8080

        # --- Resources Block ---
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "512m"

        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-db-env
              key: DB_HOST

        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: mysql-db-env
              key: DB_PORT

        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: mysql-db-env
              key: DB_NAME

        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-db-env
              key: DB_USER

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: db-password