global:
  scrape_interval: 15s # Collect data every 15 sec

scrape_configs:
  # 1. Prometheus Self Matrix 
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 2. SkillPulse Backend Matrix
  - job_name: 'skillpulse-backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend-service:8080']