name: CD

on:
  workflow_call:
    inputs:
      EC2_HOST:
        required: true
        type: string
      EC2_USER:
        required: true
        type: string
    secrets:
      EC2_SSH_KEY:
        required: true
      ENV_FILE:
        required: true

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if [ ! -d ~/skillpulse ]; then
              git clone ${{ github.server_url }}/${{ github.repository }}.git ~/skillpulse
            fi
            cd ~/skillpulse
            git pull origin main
        
            echo '${{ secrets.ENV_FILE }}' > .env

            docker compose pull
            docker compose up -d
            docker image prune -f
