name: Code Analysis
on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true
        
jobs:
    code-analysis:
        name: SonarCloud Scan
        runs-on: ubuntu-latest
        steps:
          - name: SonarCloud Scan
            uses: SonarSource/sonarqube-scan-action@v5
            env:
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # Your authentication token
            with:
              args: 
                  -Dsonar.organization=sachinthokal
                  -Dsonar.projectKey=SkillPulse
                  -Dsonar.sources=src/
                  -Dsonar.qualitygate.wait=true