name: Reusable Code Stage Workflow

on:
  workflow_call:
    inputs:
      sonar_project_key:
        required: true
        type: string
    secrets:
      SONAR_TOKEN:
        required: true
      SONAR_HOST_URL:
        required: true

jobs:
  code_analysis:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Git (Version Control) - Code Checkout
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      # Step 2: Trivy (Secret Scanning)
      - name: Run Trivy Secret Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          hide-progress: false
          format: 'table'
          exit-code: '1'  # Fail the job if any secrets are found

      # Step 3: SonarQube (SAST) - Static Code Analysis
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=${{ inputs.sonar_project_key }}