name: Code Analysis
on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true
        
jobs:
    code-analysis:
        name: SonarCloud Scan
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v6
              
          - name: SonarCloud Scan
            uses: SonarSource/sonarqube-scan-action@v6
            env:
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # Your authentication token
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              args: >
                -Dsonar.organization=sachinthokal
                -Dsonar.projectKey=sachinthokal_SkillPulse_App
                -Dsonar.sources=.
                -Dsonar.qualitygate.wait=true