name: "SKILLPULSE ArgoCD"

on:
  workflow_call:

jobs:
  argo-deploy:
    name: "Non-Prod-ArgoCD"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install ArgoCD & Substitute Variable
      run: echo "Deploy Through ArgoCD"