name: Main DevSecOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-stage:
    name: CODE STAGE
    uses: sachinthokal/SkillPulse_App/.github/workflows/code-analysis.yml@main
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-stage:
    name: BUILD STAGE
    needs: code-stage
    uses: sachinthokal/SkillPulse_App/.github/workflows/ci.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}