name: SKILLPULSE DevSecOps Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# on:
#   workflow_dispatch:

jobs:
  code-stage:
    name: CODE
    uses: sachinthokal/SkillPulse_App/.github/workflows/code-analysis.yml@main
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-stage:
    name: BUILD
    needs: code-stage
    uses: sachinthokal/SkillPulse_App/.github/workflows/ci.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build-infra:
    name: BUILD
    needs: test-stage
    uses: sachinthokal/SkillPulse_App/.github/workflows/terraform-kind-cluster.yml@main

  test-stage:
    name: TEST
    needs: build-stage
    uses: sachinthokal/SkillPulse_App/.github/workflows/test.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy-stage:
    name: DEPLOY / Non-Prod
    needs: build-infra
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to KinD Cluster
        run: |
          echo "Deploying to KinD cluster..."
          # Here you would add the actual deployment commands, e.g., using kubectl or helm
          # For example:
          # kubectl apply -f k8s/deployment.yaml
          echo "Deployment to KinD cluster completed."

  deploy-prod:
    name: DEPLOY
    needs: deploy-stage
    uses: sachinthokal/SkillPulse_App/.github/workflows/cd.yml@main
    secrets:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      ENV_FILE: ${{ secrets.ENV_FILE }}

  infra-clean:
    name: "Delete Non-Prod Infra"
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Terraform Kind Cluster Check
        run: |
          cd ~/Sachin_Workspace/projects/SkillPulse_App/Terraform/local-kind-cluster/
          if kind get clusters | grep -q "^terraform-east-cluster$"; then
            echo "Cluster exists, deleting..."
            terraform destroy
          fi
          echo "Cluster does not exist, Exited..."          
          echo "Successfully Deleted KinD cluster using Terraform."
