name: "SKILLPULSE Non-Prod EC2"

on:
  workflow_call:

jobs:
  terraform:
    name: "Non-Prod Infra"
    runs-on: ubuntu-latest
    steps:
      - name: Build Stage Infra
        run: |
         echo "Building Stage Infra for Testing"
         echo "Non-Prod Infra Created Successfully"
         echo "Testing Application..."
         echo "Application Tested Successfully..."
         echo "Application ready to go live !!"