name: "Terraform KinD on Local Machine"

on:
  workflow_dispatch: 

jobs:
  terraform:
    name: "Non-Prod Infra"
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Working Directory
        run: |
          echo "Current working directory: $(pwd)"
          cd Terraform/local-kind-cluster
          ls -la
          terraform --version

      - name: Terraform Init
        run: terraform init
