name: "Terraform KinD on Local Machine"

on:
  workflow_call:

jobs:
  terraform:
    name: "Non-Prod Infra"
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Infra with Terraform
        run: |

          cd ./SkillPulse_App/Terraform/local-kind-cluster

          terraform init
          terraform plan -var-file="terraform.tfvars" >> ${GITHUB_STEP_SUMMARY}
          terraform apply -var-file="terraform.tfvars" -auto-approve >> ${GITHUB_STEP_SUMMARY}
          echo "Terraform applied successfully." >> ${GITHUB_STEP_SUMMARY}

      - name: Verify Kind Cluster
        run: |
          kind get clusters >> ${GITHUB_STEP_SUMMARY}
          echo "Kind cluster verification completed." >> ${GITHUB_STEP_SUMMARY}
      
      - name: Report Terraform Output
        run: |
          terraform output >> ${GITHUB_STEP_SUMMARY}
          echo "Terraform output reported successfully." >> ${GITHUB_STEP_SUMMARY}