name: "Terraform KinD on Local Machine"

on:
  workflow_dispatch: 

jobs:
  terraform:
    name: "Non-Prod Infra"
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Terraform Kind Cluster Check
        run: |
          if kind get clusters | grep -q "^terraform-east-cluster$"; then
            echo "Cluster exists, deleting..."
            kind delete cluster --name terraform-east-cluster
          fi

          echo "Cluster does not exist, proceeding..."
          
      - name: Deploy to KinD Cluster using Terraform  
        run: |
          cd Terraform/local-kind-cluster
          echo "${{ vars.TFVARS_CONTENT }}" > terraform.tfvars
          echo " " > terraform.tfvars
          ls -la
          cat terraform.tfvars

          terraform init
          terraform plan
          terraform apply -auto-approve
          
          terraform output -json > terraform_output.json
          echo "### Terraform Output" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`json" >> $GITHUB_STEP_SUMMARY
          cat terraform_output.json >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          
          echo "Successfully deployed KinD cluster using Terraform."
