name: "Delete Terraform KinD Cluster"

on:
  workflow_call:

jobs:
  terraform:
    name: "Non-Prod Infra"
    runs-on: self-hosted
    env:
      TFVARS_CONTENT: ${{ vars.TFVARS_CONTENT }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Terraform Kind Cluster Check
        run: |
          if kind get clusters | grep -q "^terraform-east-cluster$"; then
            echo "Cluster exists, deleting..."
            kind delete cluster --name terraform-east-cluster
          fi

          echo "Cluster does not exist, proceeding..."
          
      - name: Deploy to KinD Cluster using Terraform  
        run: |
          cd ~/Sachin_Workspace/projects/SkillPulse_App/Terraform/local-kind-cluster/
          echo "$TFVARS_CONTENT" > terraform.tfvars
          ls -la
          cat terraform.tfvars

          terraform destroy
          
          terraform output -json > terraform_output.json
          echo "### Terraform Output" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`json" >> $GITHUB_STEP_SUMMARY
          cat terraform_output.json >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          
          echo "Successfully Deleted KinD cluster using Terraform."
