name: "SKILLPULSE Terraform EC2 Cluster"

on:
  workflow_call:

jobs:
  terraform:
    name: "Terraform-Stage-Infra"
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # STEP 1: Run Terraform Plan
      - name: Terraform Plan
        id: plan
        working-directory: ./Terraform
        run: |

          ls -la
          pwd
          terraform init
          terraform plan -detailed-exitcode -out=tfplan || exit_code=$?
          echo "exit_code=$exit_code"
          
          if [ "$exit_code" -eq 0 ]; then
            echo "changes_present=false" >> $GITHUB_OUTPUT
            echo "No infrastructure changes detected. Keeping existing setup." >> $GITHUB_STEP_SUMMARY
          elif [ "$exit_code" -eq 2 ]; then
            echo "changes_present=true" >> $GITHUB_OUTPUT
          else
            echo "Terraform plan failed with error code $exit_code"
            exit $exit_code
          fi

          ls -la
          pwd

      - name: Terraform Apply
        if: steps.plan.outputs.changes_present == 'true'
        working-directory: ./Terraform
        run: |
          terraform apply -auto-approve tfplan 
          terraform output >> $GITHUB_STEP_SUMMARY