name: "SKILLPULSE Terraform KinD Cluster"

on:
  workflow_call:

jobs:
  terraform:
    name: "Non-Prod Infra"
    runs-on: self-hosted
    env:
      TFVARS_CONTENT: ${{ vars.TFVARS_CONTENT }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Terraform Kind Cluster & State Check
        run: |
          cd ~/Sachin_Workspace/projects/SkillPulse_App/Terraform/local-kind-cluster/
          
          if kind get clusters | grep -q "^terraform-east-cluster$"; then
            echo "KinD Cluster exists in Docker, deleting..."
            kind delete cluster --name terraform-east-cluster
          fi

          if [ -f "terraform.tfstate" ]; then
            echo "Syncing Terraform state..."
            terraform init
            terraform state rm kind_cluster.default || echo "State already clear"
          fi

          echo "Cluster and state are clean, proceeding..."
          
      - name: Deploy to KinD Cluster using Terraform  
        run: |
          cd ~/Sachin_Workspace/projects/SkillPulse_App/Terraform/local-kind-cluster/
          echo "$TFVARS_CONTENT" > terraform.tfvars
          ls -la
          cat terraform.tfvars

          terraform init
          terraform plan
          terraform apply -auto-approve
          
          terraform output -json > terraform_output.json
          echo "### Terraform Output" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`json" >> $GITHUB_STEP_SUMMARY
          cat terraform_output.json >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          
          echo "Successfully deployed KinD cluster using Terraform."