name: SKILLPULSE DAST

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
        
jobs:
  test:
    name: Trivy Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Login to Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Trivy Backend Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/skillpulse-backend:latest
          format: 'table'
          exit-code: '1'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
    
      - name: Trivy Frontend Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/skillpulse-frontend:latest
          format: 'table'
          exit-code: '1'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Publish Trivy Scan Results to UI
        if: always() # Ensure this step runs even if the previous ones fail
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          echo "### 🚀 Trivy Scan Results - Backend Image" >> $GITHUB_STEP_SUMMARY
          echo "#### Image: docker.io/$DOCKERHUB_USERNAME/skillpulse-backend:latest" >> $GITHUB_STEP_SUMMARY
          echo '```text' >> $GITHUB_STEP_SUMMARY
          trivy image --format table --severity CRITICAL,HIGH docker.io/$DOCKERHUB_USERNAME/skillpulse-backend:latest >> $GITHUB_STEP_SUMMARY || true
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          echo "### 🚀 Trivy Scan Results - Frontend Image" >> $GITHUB_STEP_SUMMARY
          echo "#### Image: docker.io/$DOCKERHUB_USERNAME/skillpulse-frontend:latest" >> $GITHUB_STEP_SUMMARY
          echo '```text' >> $GITHUB_STEP_SUMMARY
          trivy image --format table --severity CRITICAL,HIGH docker.io/$DOCKERHUB_USERNAME/skillpulse-frontend:latest >> $GITHUB_STEP_SUMMARY || true
          echo '```' >> $GITHUB_STEP_SUMMARY