name: SKILLPULSE TEST

on:
  workflow_call:
    secrets:
        DOCKERHUB_USERNAME:
            required: true

jobs:
  test:
    name: Test SKILLPULSE
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Trivy Backend Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/skillpulse-backend:latest
          format: 'table'
          exit-code: '1'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
    
      - name: Trivy Frontend Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/skillpulse-frontend:latest
          format: 'table'
          exit-code: '1'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'